---
abstract: 'Proxy for sproradically-used web application'
author:
  - 'Yanick Champoux <yanick@babyl.dyndns.org>'
build_requires:
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Module::Build: '0.3601'
  Test::More: '0.88'
configure_requires:
  Module::Build: '0.3601'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-Ringleader
provides:
  App::Ringleader:
    file: lib/App/Ringleader.pm
    version: v0.1.0
requires:
  CHI: '0'
  HTTP::Proxy: '0'
  HTTP::Proxy::HeaderFilter::simple: '0'
  MooseX::App::Simple: '0'
  Path::Tiny: '0'
  Ubic: '0'
  YAML::XS: '0'
  perl: v5.10.0
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/yanick/App-Ringleader/issues
  homepage: http://search.cpan.org/dist/App-Ringleader/
  repository: https://github.com/yanick/App-Ringleader.git
version: 0.1.0
x_author_pledge:
  version: 1
x_authority: cpan:YANICK
x_contributors:
  - 'Yanick Champoux <yanick@cpan.org>'
